// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameColor = "colors"

// Color mapped from table <colors>
type Color struct {
	ID   int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Date int32   `gorm:"column:date;type:int;not null;index:c_date_mkt,priority:1" json:"date"`
	Mkt  string  `gorm:"column:mkt;type:text;not null;index:c_date_mkt,priority:2" json:"mkt"`
	Hex  string  `gorm:"column:hex;type:char(6);not null;index:idx_hex,priority:1" json:"hex"`
	RgbR int32   `gorm:"column:rgb_r;type:tinyint unsigned;not null;index:idx_rgb,priority:1" json:"rgb_r"`
	RgbG int32   `gorm:"column:rgb_g;type:tinyint unsigned;not null;index:idx_rgb,priority:2" json:"rgb_g"`
	RgbB int32   `gorm:"column:rgb_b;type:tinyint unsigned;not null;index:idx_rgb,priority:3" json:"rgb_b"`
	LabL float64 `gorm:"column:lab_l;type:double;not null;index:idx_lab,priority:1" json:"lab_l"`
	LabA float64 `gorm:"column:lab_a;type:double;not null;index:idx_lab,priority:2" json:"lab_a"`
	LabB float64 `gorm:"column:lab_b;type:double;not null;index:idx_lab,priority:3" json:"lab_b"`
}

// TableName Color's table name
func (*Color) TableName() string {
	return TableNameColor
}
