// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImg2 = "img2"

// Img2 mapped from table <img2>
type Img2 struct {
	ID           int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Date         int32  `gorm:"column:date;type:int;not null;uniqueIndex:date_mkt,priority:1" json:"date"`
	Blurhash     string `gorm:"column:blurhash;type:text;not null" json:"blurhash"`
	Color        string `gorm:"column:color;type:text;not null" json:"color"`
	Height       int64  `gorm:"column:height;type:int;not null" json:"height"`
	Width        int64  `gorm:"column:width;type:int;not null" json:"width"`
	Headline     string `gorm:"column:headline;type:text;not null;index:headline,priority:1" json:"headline"`
	Description  string `gorm:"column:description;type:text;not null;index:description,priority:1" json:"description"`
	QuickFact    string `gorm:"column:quick_fact;type:text;not null;index:quick_fact,priority:1" json:"quick_fact"`
	TriviaURL    string `gorm:"column:trivia_url;type:text;not null" json:"trivia_url"`
	URL          string `gorm:"column:url;type:text;not null" json:"url"`
	Name         string `gorm:"column:name;type:text;not null;index:name,priority:1" json:"name"`
	Market       string `gorm:"column:market;type:text;not null;uniqueIndex:date_mkt,priority:2" json:"market"`
	Hash         string `gorm:"column:hash;type:text;not null" json:"hash"`
	BackstageURL string `gorm:"column:backstage_url;type:text;not null" json:"backstage_url"`
	Copyright    string `gorm:"column:copyright;type:text;not null;index:copyright,priority:1" json:"copyright"`
	Title        string `gorm:"column:title;type:text;not null;index:title,priority:1" json:"title"`
}

// TableName Img2's table name
func (*Img2) TableName() string {
	return TableNameImg2
}
